---
title: "Molecular Cloning Summary"
author: "Te"
date: "2022-11-08"
categories: [news, code, analysis]
---

## 分子克隆总结

软件及网络工具：SnapGene , NEB Cloner 等

连接方式：

- Gibson Assembly, T4 ligase, Gateway, Infusion, TOPO etc.  
- Gibson Assembly:（5-6个片段连接同样有效，如果受条件制约试剂可以自行配置）
- TEDA Cloning(super-money-saving)

► 优点：No scar, gene 可以连续连接并且没有“接缝”

► 可以增加序列 
 也可以删除序列用于制造 将某个基因敲出， 引物合成的时候自然丢掉它
 
► 注意点：因为它会将5‘端 chowing back ，Vector的线性化是单一酶切位点切开线性化的，请注意它的粘性末端sticky end，5' overhang 回导致被chowing back and disappear。如果不特意在引物中设计将原有酶切位点序列加以保留，连接后就会损失了这个酶切位点。
Tool box in NEB url: https://nebuilder.neb.com/ （可以选择是否修复酶切位点，in case you lost it for further use）

► 特殊情况处理：如果遇到不能利用单一酶切位点线性化Vector怎么办?（ 如基因当中存在酶切位点，如果切开Vector同时会导致基因断裂）直接利用Overlap site:homology sequence 进行连接，有些片段可以用PCR的方式（推荐使用高保真Q5 polymerase，但是这个酶合成序列后是Blunt end，如果进一步构建library文库可以用Taq酶+dATP, 加入到PCR纯化后的产物中进行修复A tail, 找不到dATP就用dNTP（ATGC混合物），实际使用上没有差别），或者用单核苷酸序列（Oligos）人工合成序列（合成互补的两条链同时直接加入你想改造的想法：如加入突变的位点或者Kozak序列或者加入Mutiple cloning sites(poly-linker等)，不必一次合成过长价格很贵序列错率高，利用Gibson Assembly的优势分段合成组合即可）

► Tips:人工合成两条Oligos 你甚至可以直接考虑他们互补配对后自然就有stricky end,这样就省去了PCR->跑胶->切胶纯化的步骤。
此外PCR产物可以考虑使用PCR purification Kit进行纯化，如果模板使用了一个完整的质粒，由于质粒是有甲基化位点的，而PCR没有甲基化位点可以用DpnI 酶先Digestion 然后Heat inactive 进行纯化。（能不跑胶就不要做，浪费时间，最后回收的DNA含有agarose也会影响连接的效率）。
不切的Vector酶的意义,许多人忽略不切Vector酶的意义然而这些酶如果在引物当中引入homology sequence-uncut restiction enzyme site sequece-homology seuquence 利用Gibson Assembly 一连接自然而然加入了克隆位点用于后期加装各种调控元件。

## T4 ligase （用好了同样很厉害）
  1.突变及Oligos的使用参考Gibson Assembly的描述  
  2.根据条件适度选择Cloning Strategy  

## TOPO克隆
  1.为了保真性 用Q5酶PCR 然后用Taq酶修复A tail  
  2.TOPO克隆阳性率极好，但注意连入的片段有正向的也有反向的  
  3.如果想连接TOPO克隆的两个片段（想法极其罕见，my previous boss did this, because our fusion pcr does not work,actually I feel amazing when he came up with the idea use two reverse oritation amplicons to assemble it together, details show below) 
  
**昨日旧梦，一把辛酸泪！不过虽然结果不好，困苦中终于把克隆基础打的特别扎实！**
