---
title: Draw a 96 wells with ggplot2
author: Guo Te
date: '2022-09-13'
slug: draw-a-96-wells-with-ggplot2
categories:
  - R
tags:
  - R Markdown
---
```{r warning=FALSE, message=FALSE}
library(tidyverse)

# Generate "well" coordinates x , y
y <- LETTERS[1:8]
x <- 1:12

# Generate all the x, y combination and put into data.frame "plate"
plate <- expand.grid(x,y)

# Draw a 96-well
# levels = LETTERS[8:1] to keep  "A" to "H" at y-axis
ggplot(plate,aes(Var1,factor(Var2,levels = LETTERS[8:1])))+
  geom_point(size=8,color="#a2d2ff")+
  scale_x_continuous(breaks = seq(1,12,by=1), position = "top")+
  scale_y_discrete(breaks=LETTERS[1:8])+
  labs(x=NULL,
       y=NULL)+
  theme_bw()+
  theme(legend.position = "none")
```

Update version without set y level
```{r warning=FALSE, message=FALSE}
library(tidyverse)

# Generate "well" coordinates x , y
y <- LETTERS[8:1] # just change LETTERS[1:8] to  LETTERS[8:1]
x <- 1:12

# Generate all the x, y combination and put into data.frame "plate"
plate <- expand.grid(x,y)

# Draw a 96-well

ggplot(plate,aes(Var1,Var2, color=Var2))+
  geom_point(size=8)+
  scale_x_continuous(breaks = seq(1,12,by=1), position = "top")+
  scale_y_discrete(breaks=LETTERS[1:8])+
  labs(x=NULL,
       y=NULL)+
  theme_bw()+
  theme(legend.position = "none")
```

