---
title: ggplot-theme-fonts-example
author: Guo Te
date: '2022-09-08'
slug: ggplot-theme-fonts-example
categories:
  - R
tags:
  - R Markdown
---
# load fonts
```{r}
# initial configuration
windowsFonts()
# load new font
sysfonts::font_add_google("Roboto", family = "Roboto")
sysfonts::font_add_google("Lato", family = "Lato")
sysfonts::font_families()

# use it
showtext::showtext_auto()
```

# load library 
```{r warning=FALSE,message=FALSE}

library(tidyverse)
df <- tibble(ChickWeight)
ggplot(df, aes(Time, weight, group = Diet, color = Diet)) +
  geom_smooth(aes(group = Diet), se = FALSE) +
  theme(
    axis.title = element_text(size = 16, family = "Roboto"),
    axis.text.x = element_text(size = 12, family = "Roboto"),
    axis.text.y = element_text(size = 12, family = "Roboto"),
    plot.title = element_text(size = 20, face = "bold", color = "red2", family = "Lato"),
    plot.subtitle = element_text(size = 14, color = "blue4", family = "Lato"),
    axis.line.x = element_line(color = "gray8"),
    axis.line.y = element_line(color = "gray8"),
    panel.background = element_rect(fill = "white"),
    plot.background = element_rect(fill = "white"),
    legend.position = c(0.1, 0.8),
    legend.background = element_rect(fill = NA),
    legend.key = element_rect(fill = NA),
    plot.margin = unit(c(.5, .5, .5, .5), "cm")
  ) +
  labs(
    title = "Effect of different feeds on body weight of chicks",
    subtitle = "After 20 days Diet3 is much better ",
    y = "Chick Weight (g)",
    x = "Day"
  )
ggsave(filename = "ChickWeight.pdf", plot = last_plot(), height = 6, width = 8)
```
# pdf convert to png
```{r}

pdftools::pdf_convert(
  pdf = "ChickWeight.pdf",
  filenames = "ChickWeight.png",
  format = "png", 
  dpi = 200
)
```
