---
title: "R中自动画流程图"
author: "Te"
date: "2022-11-08"
categories: [news, code, analysis]
---

## R中自动画流程图

### DiagrammeR::grViz实践中的应用(初试)
**分子克隆的一般思路简图**

说明

- 无缝克隆要留有足够的同源序列
- 平末端可以采用  
     1. 无缝克隆（保留足够长同源序列）
     2. T4 ligase克隆（Vector去磷酸化（防止自联）, Insert磷酸化）

> 个人感觉：非常混乱的语言模式，但是又没有什么好的选择

```{r, echo=FALSE}
library(DiagrammeR)

grViz("
digraph flowchat{

  # several 'node' statements
  node [shape = circle, fontname = Helvetica, fillcolor='#e9a3c9', color='#e9a3c9',style=filled]
  Vector; Insert
  # set other 'node's statements
  node [shape = rect, fontname = Helvetica, color='#a1d76a', fillcolor='#a1d76a', style=filled]
  
  # several 'edge' statements
  edge[color='#0a9396',style=filled,arrowhead=vee]
  
  Vector-> 'PCR or Synthesis'->Linearized
  Linearized->Seamless_Cloning
  Vector->'Non-linearized'->Digestion->Purification->Linearized->Ligation
  Insert->Sticky_end->Ligation
  Insert->Blunt_end -> Seamless_Cloning->New_Plasmid
  Ligation->New_Plasmid
  
  New_Plasmid[fillcolor='#ffcb77',style=filled,color='#ffcb77'] 
  # must add style=filled otherwise does not work with fillcolor
  
  subgraph {
  rank = same; Vector; Insert; }
  
  subgraph {
  rank = same; Linearized; Blunt_end; Sticky_end; }
   
}",height = 600)
```
### Code part
```{r, echo=TRUE, results='hide'}
library(DiagrammeR)

grViz("
digraph flowchat{

  # several 'node' statements
  node [shape = circle, fontname = Helvetica, fillcolor='#e9a3c9', color='#e9a3c9',style=filled]
  Vector; Insert
  # set other 'node's statements
  node [shape = rect, fontname = Helvetica, color='#a1d76a', fillcolor='#a1d76a', style=filled]
  
  # several 'edge' statements
  edge[color='#0a9396',style=filled,arrowhead=vee]
  
  Vector-> 'PCR or Synthesis'->Linearized
  Linearized->Seamless_Cloning
  Vector->'Non-linearized'->Digestion->Purification->Linearized->Ligation
  Insert->Sticky_end->Ligation
  Insert->Blunt_end -> Seamless_Cloning->New_Plasmid
  Ligation->New_Plasmid
  
  New_Plasmid[fillcolor='#ffcb77',style=filled,color='#ffcb77'] 
  # must add style=filled otherwise does not work with fillcolor
  
  subgraph {
  rank = same; Vector; Insert; }
  
  subgraph {
  rank = same; Linearized; Blunt_end; Sticky_end; }
   
}",height = 600)
```
