---
title: Bar plot with labels ggfittext
author: "Te"
date: "2023-06-02"
categories: [news, code, analysis]
---

```{r warning=FALSE,message=FALSE}
# data from 王敏杰 老师
# his book https://bookdown.org/wangminjie/R4DS/author.html

d <- tibble::tribble(
     ~name, ~value,
   "Alice",   2.12,
     "Bob",  68.45,
  "Carlie",  15.84,
    "Dave",   7.38,
     "Eve",   0.56
  )


library(tidyverse)
library(ggfittext)

d %>% 
  ggplot(aes(x = value, y = fct_reorder(name, value)) ) +
  geom_col(width = 0.6, fill = "gray45") +
  geom_text(aes(label = value, hjust = 1))  +
  theme_classic() +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = NULL, y = NULL)
```

```{r warning=FALSE,message=FALSE}
# ggfittext to adjust the text position
d %>% 
  ggplot(aes(x = value, y = fct_reorder(name, value)) ) +
  geom_col(width = 0.6, fill = "#99d594") +
  scale_x_continuous(expand = c(0, 0)) +
  geom_bar_text(aes(label = d$value), 
                color = "blue", 
                vjust = 1, 
                # size = 4 * ggplot2::.pt, 
                # min.size = 4 * ggplot2::.pt,
                # padding.x = grid::unit(0, "pt"),
                # padding.y = grid::unit(0, "pt"),
                outside = TRUE)+
  labs(x = "",
       y = "",
       title="Welcome Kai to visit here")+
  theme_classic()
```
